import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  localStorage.setItem('authkey','authkey_0000')
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Products</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/passwordreset">Passwordreset</Link>
        </li>
        <li>
          <Link to="/emailconfirmation">Emailconfirmation</Link>
        </li>
        <li>
          <Link to="/registrationcomplete">Registrationcomplete</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/addproducts">Addproducts</Link>
        </li>
        <li>
          <Link to="/orders">Orders</Link>
        </li>
        <li>
          <Link to="/article">Article</Link>
        </li>
        <li>
          <Link to="/customers">Customers</Link>
        </li>
        <li>
          <Link to="/customerinfo">Customerinfo</Link>
        </li>
        <li>
          <Link to="/addcustomer">Addcustomer</Link>
        </li>
        <li>
          <Link to="/settingsnotifications">Settingsnotifications</Link>
        </li>
        <li>
          <Link to="/productsemptyone">ProductsemptyOne</Link>
        </li>
        <li>
          <Link to="/productsempty">Productsempty</Link>
        </li>
        <li>
          <Link to="/categoriesempty">Categoriesempty</Link>
        </li>
        <li>
          <Link to="/customersempty">Customersempty</Link>
        </li>
        <li>
          <Link to="/frame1116606593">Frame1116606593</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
